import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import assert from 'node:assert/strict';
const db=new PGlite(),ws=randomUUID(),other=randomUUID(),owner=randomUUID(),reader=randomUUID(),outsider=randomUUID(),token=randomUUID();
await db.exec(`create role authenticated;create role anon;create role service_role bypassrls;create schema auth;
create table auth.users(id uuid primary key);create table workspaces(id uuid primary key,owner_user_id uuid);
create table workspace_members(workspace_id uuid,user_id uuid,permissions jsonb);
insert into auth.users values('${owner}'),('${reader}'),('${outsider}');insert into workspaces values('${ws}','${owner}'),('${other}','${outsider}');
insert into workspace_members values('${ws}','${reader}','["progress.view"]');
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
create function is_workspace_owner(id uuid) returns boolean language sql stable security definer as $$ select exists(select 1 from workspaces where workspaces.id=$1 and owner_user_id=auth.uid()) $$;
grant usage on schema auth to authenticated,anon;`);
await db.exec(readFileSync('supabase/migrations/202610100001_printer_monitor.sql','utf8'));
await db.query('insert into printer_cloud_connections(workspace_id,sealed_session,connected_by) values($1,$2,$3)',[ws,'{"cipher":"private"}',owner]);
const claim=async(lease=token)=>(await db.query('select claim_printer_monitor($1,$2) ok',[ws,lease])).rows[0].ok;
await db.exec('set role service_role');assert.equal(await claim(),true);assert.equal(await claim(randomUUID()),false,'Only one active producer');
assert.equal((await db.query('select claim_printer_login_code($1) ok',[ws])).rows[0].ok,true);assert.equal((await db.query('select claim_printer_login_code($1) ok',[ws])).rows[0].ok,false,'Email cooldown is enforced on the server');
const event={id:'A:1',type:'printer_warning',severity:'warning'},run={id:'run-1',deviceId:'A',printingMs:10};
const commit=async(lease=token,events=[event],runs=[run])=>db.query('select commit_printer_monitor($1,$2,$3,$4,$5)',[ws,lease,'{"devices":{"A":{}}}',JSON.stringify(events),JSON.stringify(runs)]);
await commit();await commit();assert.equal((await db.query('select count(*)::int n from printer_monitor_events')).rows[0].n,1,'Retry is idempotent');
await assert.rejects(()=>commit(randomUUID()),e=>e.code==='40001','Stale producers cannot overwrite');
await db.exec('reset role');await db.exec(`update printer_monitor_runs set linked_models='[{"modelId":"kept"}]',links_revision='2026-10-10'`);await db.exec('set role service_role');await commit(token,[],[{...run,printingMs:20}]);
assert.equal((await db.query('select linked_models from printer_monitor_runs')).rows[0].linked_models[0].modelId,'kept','Telemetry must not overwrite manual model links');
await assert.rejects(()=>commit(token,[{bad:true}],[{...run,printingMs:999}]),e=>e.code==='23502');assert.equal((await db.query('select data from printer_monitor_runs')).rows[0].data.printingMs,20);
await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[reader]);await db.exec('set role authenticated');
assert.equal((await db.query('select count(*)::int n from printer_monitor_events')).rows[0].n,1);await assert.rejects(()=>db.query('select sealed_session from printer_cloud_connections'),/permission denied/);
await assert.rejects(()=>claim(),/permission denied/);await assert.rejects(()=>commit(),/permission denied/);await assert.rejects(()=>db.query('delete from printer_monitor_runs'),/permission denied/);
await assert.rejects(()=>db.query('select claim_printer_login_code($1)',[ws]),/permission denied/);
await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[outsider]);await db.exec('set role authenticated');assert.equal((await db.query('select count(*)::int n from printer_monitor_events')).rows[0].n,0,'Cross-workspace records cannot be read');
await db.exec('reset role');await db.exec('delete from printer_cloud_connections');assert.equal((await db.query('select count(*)::int n from printer_monitor_runs')).rows[0].n,1,'Disconnect keeps saved history');
await db.close();console.log('PASS printer SQL: RLS, private credentials, producer lease, atomic rollback, idempotency, model-link isolation, preserved history.');
