import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {applyTelemetry,applyPresence,issueFor,warningKey,canIgnore,matchTask} from '../printer-core.mjs';
import {packet,PacketDecoder,connectPacket,subscribePacket,snapshotPacket,monitorMqtt} from '../supabase/functions/bambu-monitor/mqtt.mjs';
const device={id:'printer-A',name:'Mỹ Mỹ',model:'A1'},at=seconds=>new Date(Date.UTC(2026,9,10,0,0,seconds)).toISOString();
let state=null;const next=(print,seconds)=>{const result=applyTelemetry(state,device,{print},at(seconds));state=result.state;return result;};
const first=next({gcode_state:'RUNNING',task_id:'10',subtask_id:'11',mc_percent:45,layer_num:2,mc_remaining_time:30,hms:[{attr:0x03000100,code:0x00030001}]},0);
assert.equal(state.percent,45);assert.equal(state.run.startedObservedAt,null);assert.equal(state.run.gap,true);assert.equal(first.events.filter(e=>e.type==='printer_started').length,0);
assert.equal(state.issues[0].severity,'warning');assert.equal(canIgnore(state.issues[0]),true);assert.equal(canIgnore({severity:'error'}),false);
const key=warningKey(device.id,state.issues[0]);assert.equal(next({nozzle_temper:220},10).events.length,0);assert.equal(state.percent,45);assert.equal(warningKey(device.id,state.issues[0]),key,'Delta without HMS retains the episode');
const partialRun=state.run.id;next({task_id:'10'},11);assert.equal(state.run.id,partialRun,'Parent-only delta does not replace the subtask identity');assert.equal(state.taskId,'11');
assert.equal(next({gcode_state:'PAUSE'},20).events[0].type,'printer_paused');assert.equal(state.run.printingMs,20000);
assert.equal(next({gcode_state:'RUNNING'},30).events[0].type,'printer_resumed');assert.equal(state.run.pausedMs,10000);
assert.equal(next({gcode_state:'RUNNING'},31).events.length,0,'No replay popup');
next({hms:[]},32);assert.equal(state.issues.length,0);assert.equal(next({hms:[{attr:0x03000100,code:0x00030001}]},33).events[0].severity,'warning');assert.notEqual(warningKey(device.id,state.issues[0]),key);
const priorRun=state.run.id;assert.equal(next({gcode_state:'RUNNING',subtask_id:'22'},34).events[0].type,'printer_started');assert.notEqual(state.run.id,priorRun);assert.equal(state.run.printingMs,0);assert.equal(state.issues.length,1,'Changing jobs does not erase unconfirmed hardware warnings');
assert.equal(next({print_error:2},35).events[0].type,'printer_error');assert.equal(state.phase,'RUNNING','An issue is not a fake gcode phase');
const done=next({gcode_state:'FINISH'},45);assert.equal(done.events[0].type,'printer_finished');assert.equal(state.run.endedObservedAt,at(45));assert.equal(state.run.result,'finished');
assert.equal(next({gcode_state:'FINISH'},46).events.length,0);
const noTime=JSON.stringify(state);assert.deepEqual(applyTelemetry(state,device,{foo:{}},at(50)).events,[]);assert.equal(JSON.stringify(state),noTime);
state=applyPresence(state,false,at(50)).state;assert.equal(next({nozzle_temper:200},51).events[0].type,'printer_reconnected');
assert.equal(applyPresence(state,null,at(51)).state.online,true,'Missing bind presence is unknown, not an offline transition');assert.equal(applyPresence(state,undefined,at(51)).events.length,0);
next({gcode_state:'IDLE'},52);assert.equal(next({gcode_state:'RUNNING',subtask_id:'33'},400).events.filter(e=>e.type==='printer_started').length,0,'No invented start after a monitoring gap');assert.equal(state.run.startedObservedAt,null);
next({gcode_state:'FINISH'},800);assert.equal(state.run.gap,true);
assert.equal(matchTask({hits:[{id:'33',deviceId:device.id,cover:'https://test/real'},{id:'33',deviceId:'other',cover:'https://test/wrong'}]},state).cover,'https://test/real');
assert.equal(matchTask({hits:[{id:'latest',deviceId:device.id,cover:'https://test/wrong'}]},state),null);
assert.equal(matchTask({hits:[{id:'33',deviceId:device.id},{id:'33',deviceId:device.id}]},state),null,'Ambiguous identities never guess');
const parentChanged=applyTelemetry(state,device,{print:{task_id:'99',gcode_state:'RUNNING'}},at(801));assert.equal(parentChanged.state.subtaskId,'','Do not carry the previous subtask into a new cloud task');assert.equal(parentChanged.state.taskId,'99');
const catalog=JSON.parse(readFileSync('supabase/functions/bambu-monitor/hms-en.json')),vi=JSON.parse(readFileSync('supabase/functions/bambu-monitor/hms-vi.json'));
const code=Object.keys(catalog.device_hms)[0],known=issueFor('hms',code,'A1',catalog,vi);assert.ok(known.original);assert.ok(known.text);assert.notEqual(known.text,known.original);assert.match(issueFor('hms','ffffffffffffffff','A1',catalog,vi).text,/Chưa có mô tả/);
const decoder=new PacketDecoder(),bytes=packet(0x30,new Uint8Array(200).fill(7));let messages=[];for(const byte of bytes)messages.push(...decoder.push(new Uint8Array([byte])));assert.equal(messages.length,1);assert.equal(messages[0].body.length,200);
assert.throws(()=>new PacketDecoder().push(new Uint8Array([0x30,255,255,255,255,0])),/không hợp lệ/);
assert.throws(()=>new PacketDecoder().push(new Uint8Array(2200001)),/quá lớn/);
assert.equal(connectPacket('u_test','secret')[0],0x10);assert.equal(subscribePacket(['A'])[0],0x82);const raw=new TextDecoder().decode(snapshotPacket('A'));assert.match(raw,/pushall/);assert.doesNotMatch(raw,/pause|resume|speed|gcode_line/);
// Fragmented MQTT over an injected TLS connection. No real account or machine.
const report=packet(0x30,new Uint8Array([...new Uint8Array([0,19]),...new TextEncoder().encode('device/printer-A/report'),...new TextEncoder().encode('{"print":{"mc_percent":12}}')]));
// Topic length must describe the exact UTF-8 byte sequence.
const topic=new TextEncoder().encode('device/printer-A/report');report[2]=0;report[3]=topic.length;
const queue=[new Uint8Array([0x20,2,0,0]),new Uint8Array([0x90,3,0,1,0]),report],writes=[];let closed=false;
const controller=new AbortController();
await monitorMqtt(async options=>{assert.equal(options.port,8883);assert.equal(options.hostname,'us.mqtt.bambulab.com');return {async write(bytes){writes.push(bytes.slice());return bytes.length;},async read(buffer){if(!queue.length)return null;const part=queue.shift();buffer.set(part);return part.length;},close(){closed=true;}};},{username:'u_test',token:'secret',region:'Global'},[device.id],async(id,payload)=>{assert.equal(id,device.id);assert.equal(payload.print.mc_percent,12);controller.abort();},controller.signal,{requestSnapshots:[device.id]});
assert.equal(closed,true);assert.equal(writes.filter(w=>w[0]===0x30).length,1);
await assert.rejects(()=>monitorMqtt(async()=>({write:async b=>b.length,read:async b=>{b.set([0x20,2,0,5]);return 4;},close(){}}),{username:'u',token:'bad'},['A'],async()=>{},new AbortController().signal),/từ chối phiên/);
console.log('PASS printer core/MQTT: deltas, episodes, severity, task identity, gap-aware history, snapshot-only writes, framing, TLS/auth rejection.');
