import assert from 'node:assert/strict';
import {chromium} from 'playwright-core';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {mkdirSync} from 'node:fs';
const out=resolve('qa-results/printers');mkdirSync(out,{recursive:true});
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const profiles=[{width:320,height:740,touch:true},{width:390,height:844,touch:true},{width:640,height:360},{width:640,height:900},{width:1280,height:900}];
async function seed(page,theme){await page.evaluate(theme=>{
 document.documentElement.dataset.theme=theme;document.getElementById('auth-ov').style.setProperty('display','none','important');cloudReady=false;currentUser={id:'qa-user'};activeWorkspace={workspace_id:'11111111-1111-4111-8111-111111111111',owner_user_id:'qa-user'};isWorkspaceOwner=()=>true;canAccess=()=>true;
 operations={events:[],printPlans:[],deliveryBatches:[]};normalizeOperations();models=[{id:'model-1',name:'Flower Coasters — Tên model dài',images:['https://qa.invalid/model.png'],parts:[{name:'Lót ly hoa'}],variants:[{id:'large',name:'Bản lớn'}]}];
 const now=new Date().toISOString(),modelsList=['A1','A1','P1S','P1S','P2S','H2S'],devices={};
 modelsList.forEach((model,i)=>{const id='machine-'+i;devices[id]={id,name:i===0?'Mỹ Mỹ — Biệt danh dài để kiểm tra xuống dòng':'Máy '+i,model,phase:i===5?'PAUSE':'RUNNING',percent:45,layer:26,totalLayers:200,remainingMinutes:30,nozzle:220,bed:55,lastReport:now,online:true,issues:i===0?[{severity:'warning',code:'0300010000030001',text:'Cảnh báo ví dụ để kiểm tra hành vi, không phải dữ liệu xưởng.',original:'Original example text.',episode:'2026-10-10T00:00:00Z'}]:i===1?[{severity:'error',code:'0300010000020001',text:'Lỗi kiểm thử.',episode:'2026-10-10T00:00:00Z'}]:[],fileName:'Flower_Coasters.3mf',run:{id:'run-'+i,thumbnail:'https://qa.invalid/batch.png'}};});
 window.pmFixture={connected:true,state:{devices},updatedAt:now,events:[],history:[{id:'run-0',data:{id:'run-0',deviceId:'machine-0',machineName:'Mỹ Mỹ',machineModel:'A1',fileName:'Flower_Coasters.3mf',firstObservedAt:now,startedObservedAt:null,endedObservedAt:null,printingMs:60000,pausedMs:30000,gap:true,result:'running',thumbnail:'https://qa.invalid/batch.png'},linked_models:[],links_revision:now}],moreHistory:false};window.pmReads=0;window.pmSaveFailure=false;
 sb={auth:{getSession:async()=>({data:{session:{access_token:'qa-no-real-token'}}})}};
 window.fetch=async(url,options)=>{if(!String(url).includes('/bambu-monitor'))throw new Error('Blocked unrelated network request');const body=JSON.parse(options.body);if(body.action==='read'){pmReads++;window.pmLastOffset=Number(body.offset)||0;if(body.runId)return new Response(JSON.stringify({run:pmFixture.history[0]}),{headers:{'Content-Type':'application/json'}});if(body.offset)return new Response(JSON.stringify({...pmFixture,history:[],moreHistory:false}),{headers:{'Content-Type':'application/json'}});return new Response(JSON.stringify(pmFixture),{headers:{'Content-Type':'application/json'}});}if(body.action==='stream')return new Response('{"busy":true}',{headers:{'Content-Type':'application/json'}});if(body.action==='models'){if(pmSaveFailure)return new Response('{"error":"Mẻ đã đổi trên thiết bị khác. Giữ lựa chọn."}',{status:409,headers:{'Content-Type':'application/json'}});pmFixture.history[0].linked_models=body.models;return new Response('{"ok":true}',{headers:{'Content-Type':'application/json'}});}throw new Error('Unexpected action '+body.action);};
 goPage('printer-monitor',{historyMode:'none'});
 },theme);await page.waitForFunction(()=>pmReads>0&&document.querySelectorAll('.pm-machine').length===6);}
try{for(const profile of profiles)for(const theme of ['light','dark']){
 const context=await browser.newContext({viewport:{width:profile.width,height:profile.height},hasTouch:!!profile.touch,isMobile:!!profile.touch,reducedMotion:'reduce'}),page=await context.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));await context.route(/^https?:/,route=>route.abort());
 await page.goto(pathToFileURL(resolve('plate-studio.html')).href,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>!!window.PlatePrinterMonitor);await seed(page,theme);
 assert.equal(await page.locator('.page.active .production-mode').count(),3);assert.equal(await page.locator('#sidebar [data-sidebar-page="production"].active').count(),1);
 await page.waitForTimeout(250);const geometry=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth+1,inside:[...document.querySelectorAll('.pm-machine')].every(el=>el.getBoundingClientRect().right<=innerWidth+1),touch:[...document.querySelectorAll('.pm-toolbar button')].filter(el=>el.getClientRects().length).every(el=>el.getBoundingClientRect().height>=44)}));assert.deepEqual(geometry,{overflow:false,inside:true,touch:true},'Native layout and touch targets');
 const search=page.getByRole('searchbox',{name:'Tìm máy hoặc mẻ in'});await search.fill('my my');assert.equal(await page.locator('.pm-machine').count(),1,'Shared unaccented search');await search.fill('');
 await page.evaluate(()=>{window.pmKeptInput=document.querySelector('.pm-toolbar input');window.pmKeptCard=document.querySelector('.pm-machine');window.pmKeptImage=document.querySelector('.pm-machine-image');document.querySelector('.pm-toolbar input').focus();pmFixture.state.devices['machine-0'].percent=46;PlatePrinterMonitor.receive({...pmFixture,events:[]});});
 assert.ok(await page.evaluate(()=>pmKeptInput===document.activeElement&&pmKeptCard===document.querySelector('.pm-machine')&&pmKeptImage===document.querySelector('.pm-machine-image')),'Telemetry preserves search, cards and media frames');
 const details=page.locator('.pm-machine[data-device="machine-0"] .pm-issues');await details.locator(':scope > summary').click();assert.match(await details.textContent(),/Cảnh báo/);assert.match(await page.locator('.pm-machine[data-device="machine-0"] .pm-status').textContent(),/Đang in/);
 // Real transition events enter the existing popup family, not business records.
 await page.evaluate(()=>{const issue=pmFixture.state.devices['machine-0'].issues[0];const event={id:'machine-0:1',type:'printer_warning',title:'Mỹ Mỹ · Cảnh báo',detail:issue.text,deviceId:'machine-0',...issue,createdAt:new Date().toISOString()};PlatePrinterMonitor.receive({...pmFixture,events:[{seq:1,data:event}]});});
 const warning=page.locator('.system-notification-popup[data-event-id="printer:machine-0:1"]');await warning.waitFor({state:'visible'});assert.equal(await warning.locator('.pm-popup-ignore').count(),1);await warning.locator('.pm-popup-ignore').click();await page.waitForTimeout(300);assert.match(await details.textContent(),/Đã bỏ qua/);assert.equal(await details.getByRole('button',{name:'Hiện lại',exact:true}).count(),1);
 await page.evaluate(()=>{const issue=pmFixture.state.devices['machine-1'].issues[0];PlatePrinterMonitor.receive({...pmFixture,events:[{seq:2,data:{id:'machine-1:2',type:'printer_error',title:'Máy 1 · Lỗi',detail:'Lỗi kiểm thử',deviceId:'machine-1',...issue,createdAt:new Date().toISOString()}}]});});
 const error=page.locator('.system-notification-popup[data-event-id="printer:machine-1:2"]');await error.waitFor({state:'visible'});assert.equal(await error.locator('.pm-popup-ignore').count(),0,'Errors cannot use ignore warning');assert.match(await error.locator('.pm-notice-severity').textContent(),/Lỗi/);
 await page.evaluate(()=>{showSystemNotificationPopup(PlatePrinterMonitor.events().find(e=>e.id==='printer:machine-0:1'),{sound:false});});assert.equal(await warning.count(),0,'Ignored warning does not re-popup');assert.equal(await page.evaluate(()=>operations.events.length),0,'Printer messages never mutate operations history');
 await page.evaluate(()=>document.querySelectorAll('.system-notification-popup').forEach(closeSystemNotificationPopup));await page.waitForTimeout(250);
 await page.locator('[data-pm-action="history"]').click();assert.match(await page.locator('.pm-run').textContent(),/Có khoảng trống dữ liệu/);assert.match(await page.locator('.pm-run').textContent(),/Chưa ghép model/);
 assert.ok(await page.locator('.pm-model-links').evaluate(el=>el.scrollWidth<=el.clientWidth+1),'Unmapped-model explanation wraps inside history on narrow screens');
 assert.ok(await page.locator('.pm-model-links>small').evaluate(el=>{const s=getComputedStyle(el);return s.whiteSpace==='normal'&&el.scrollWidth<=el.clientWidth+1&&el.scrollHeight<=el.clientHeight+1;}),'History explanation cannot be truncated by shared text styles');
 await page.screenshot({path:resolve(out,`${profile.width}-${profile.height}-${theme}-history.png`)});
 await page.locator('[data-pm-action="models"]').click();const picker=page.locator('.pm-picker');await picker.getByRole('searchbox',{name:'Tìm model để ghép'}).fill('lot ly hoa');assert.equal(await picker.locator('.pm-model-option').count(),1);await picker.locator('[data-add][data-variant="large"]').click();assert.match(await picker.locator('.pm-picked').textContent(),/Bản lớn/);
 await picker.locator('[data-plus]').focus();await page.evaluate(()=>{window.pmKeptStepper=document.querySelector('.pm-picked input');window.pmKeptThumb=document.querySelector('.pm-picked img');});await picker.locator('[data-plus]').click();assert.equal(await picker.locator('[data-qty]').inputValue(),'2');assert.ok(await page.evaluate(()=>pmKeptStepper===document.querySelector('.pm-picked input')&&pmKeptThumb===document.querySelector('.pm-picked img')),'Picker quantities preserve existing DOM/images');
 await page.evaluate(()=>{pmSaveFailure=true;});await picker.locator('[data-save]').click();await page.waitForFunction(()=>document.querySelector('.pm-save-status')?.textContent.includes('đổi'));assert.equal(await picker.locator('[data-qty]').inputValue(),'2','Failed save keeps draft');
 page.once('dialog',dialog=>dialog.dismiss());await page.keyboard.press('Escape');assert.equal(await picker.isVisible(),true,'Escape cannot discard a dirty selection silently');
 await page.evaluate(()=>{pmSaveFailure=false;});await picker.locator('[data-save]').click();await picker.waitFor({state:'hidden'});
 await page.locator('[data-pm-action="live"]').click();await page.screenshot({path:resolve(out,`${profile.width}-${profile.height}-${theme}-live.png`)});
 await page.locator('[data-pm-action="connect"]').click();const connect=page.locator('.pm-connect');assert.match(await connect.textContent(),/Điều khiển máy chưa được/);assert.equal(await connect.locator('input[type="password"]').count(),0);await page.keyboard.press('Escape');assert.equal(await connect.isVisible(),false);
 await page.evaluate(()=>{canAccess=permission=>permission==='kiot.import';isWorkspaceOwner=()=>false;});assert.equal(await page.evaluate(()=>PlatePrinterMonitor.events().length),0,'Removing permissions immediately hides printer events');await page.evaluate(()=>goPage('printer-monitor',{historyMode:'none'}));assert.equal(await page.evaluate(()=>curPage),'dashboard','Unauthorized route blocked');
 await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>!!window.PlatePrinterMonitor);await seed(page,theme);assert.equal(await page.locator('.pm-machine[data-device="machine-0"] [data-pm-action="restore"]').count(),1,'Warning ignore survives reload');assert.match(await page.locator('.pm-machine[data-device="machine-1"] .pm-status').textContent(),/Có lỗi/,'Ignoring warning never suppresses errors');
 if(profile.width===1280&&theme==='light'){await page.evaluate(()=>{pmFixture.moreHistory=true;PlatePrinterMonitor.receive(pmFixture);});await page.locator('[data-pm-action="history"]').click();await page.locator('[data-pm-action="more"]').click();await page.waitForFunction(()=>pmLastOffset===50);await page.evaluate(()=>{activeWorkspace={...activeWorkspace,workspace_id:'22222222-2222-4222-8222-222222222222'};});await page.waitForFunction(()=>pmLastOffset===0&&document.querySelector('.pm-more')?.hidden===false);await page.locator('[data-pm-action="more"]').click();await page.waitForFunction(()=>pmLastOffset===50);assert.equal(await page.evaluate(()=>pmLastOffset),50,'Changing workspace resets the history page cursor');}
 assert.deepEqual(errors,[]);await context.close();console.log(`PASS printer UI ${profile.width}x${profile.height} ${theme}`);
}}finally{await browser.close();}
